### ISSUE TITLE
Global operators info

### ISSUE THREAD

**Issue by Kotestos** [Tabwire/R6Tab-API#10]
Hello, do you have plans to add global statistics about operators?

Something like this:
![image](https://user-images.githubusercontent.com/20170051/57762844-e6f88080-7708-11e9-9a62-a919108103f5.png)

**Comment by Kotestos** [comment]
Or this: 
![image](https://user-images.githubusercontent.com/20170051/57762974-3048d000-7709-11e9-955c-85e80b461784.png)

**Comment by AustinLeath** [comment]
We do not. Consider this issue closed, for whatever reason I don't have write access and can't close anymore.
