### ISSUE TITLE
get sorted operator

### ISSUE THREAD

**Issue by Mohsen322** [Tabwire/R6Tab-API#13]
how can i get sorted by kill or played time operator idis?
in thisa api https://r6tab.com/api/player.php?p_id=

operators and seasonOperators i need sorted

**Comment by RAYs3T** [comment]
Just use the `leaderboard.php` interface. If you need additional information for players, fetch the player api for each player by using the UUID. See main README. of the API for the parameters.

**Comment by Mohsen322** [comment]
No I mean something like this
https://r6tab.com/api/player.php?p_id=UID&type=faveOperators&sort=bykill
 or by most time played for operators defence and attack
