### ISSUE TITLE
no operator names

### ISSUE THREAD

**Issue by iNiizz** [Tabwire/R6Tab-API#14]
cannot find any names for the operators to go along with the icons... any help?

**Comment by iNiizz** [comment]
also the operators would be good if you could separate them into two objects. attackers and defenders. just to make it easier to display on the screen

**Comment by iNiizz** [comment]
@AustinLeath @Tabwire

**Comment by Tabwire** [comment]
Here are all the operators: https://github.com/Tabwire/R6Tab-API/blob/master/Operators.md

**Comment by iNiizz** [comment]
@Tabwire i know where they are but when i get the data back i only have the ID's... no names, no attacker or defender subclasses 
![Screenshot 2019-08-02 at 11 04 54](https://user-images.githubusercontent.com/53470474/62362692-6ed67580-b515-11e9-8547-82078cc0cf41.png)

**Comment by Tabwire** [comment]
You will need to do that on your script. We already provided the list of operators and their info there.

What we can do is add another section where they're available by name, but that will need few hours from us to update the API if you would like to wait.

Let me know if you will be able to do it alone or you want us to add that feature.

**Comment by iNiizz** [comment]
@Tabwire if you could add that feature, it would make things easier for new starters.

**Comment by Tabwire** [comment]
Consider it done, just give me sometime until I get all sorted out.

Note: We will not remove the old vars, we will just add new one with the operators as a tree. 

Example:
`Operator-name->`
`                             Type->(attacker,defender)`
`                             Kills->`
`                             Deaths->`
`                             Wins->`
`                             Losses->`
`                             Time-Played->`

Let me know if that will be ok for you.

**Comment by iNiizz** [comment]
sounds great to me. Thanks fo the reply!

**Comment by iNiizz** [comment]
@Tabwire quick question, is there any data for past season for example black ice/ skull rain?

**Comment by Tabwire** [comment]
No, Ubisoft lost all these data.

**Comment by iNiizz** [comment]
@Tabwire ahh thats a shame :(

**Comment by iNiizz** [comment]
@Tabwire do you know the ETA for the API Update?

**Comment by iNiizz** [comment]
@Tabwire any idea when the API will be updated?

**Comment by iNiizz** [comment]
@AustinLeath @Tabwire

**Comment by koek-blik** [comment]
Any news on this?

**Comment by iNiizz** [comment]
@leRealScrubbi nope, none at all
