### ISSUE TITLE
Support for uploading Images and get an Array of the Operators back

### ISSUE THREAD

**Issue by MrDrache333** [Tabwire/R6Tab-API#19]

**Comment by iNiizz** [comment]
i had to manipulate my function in my script to get the correct operator data...

**Comment by MrDrache333** [comment]
Do you have any working code snipped i can have a look at?

**Comment by iNiizz** [comment]
yeah

**Comment by iNiizz** [comment]
getOperators(data) {
    let IDs = [];
    let wins = [];
    let losses = [];
    let kills = [];
    let deaths = [];
    let timePlayed= [];
    let operatorsRaw = [];
  
    if (data) {
      JSON.parse(data).forEach(data => {
        operatorsRaw.push(data)
      });
      Object.keys(operatorsRaw[0]).forEach((data) => {
        IDs.push(data.replace(':', '-'));
      })
      IDs.sort();
      wins = operatorsRaw[0];
      losses = operatorsRaw[1];
      kills = operatorsRaw[2];
      deaths = operatorsRaw[3];
      timePlayed = operatorsRaw[4];
      return { IDs, wins, losses, kills, deaths,timePlayed };
    }
  }

**Comment by iNiizz** [comment]
the replace is the best way to get the images out for the operators and apply the names to the icons because they haven't put operator names in the array

**Comment by iNiizz** [comment]
im using typescript and angular 6 btw

**Comment by iNiizz** [comment]
playerSearch(playerName: string, platform) {
    return this.http.get(`https://r6tab.com/api/search.php?platform=${platform}&search=${playerName}`).pipe(
      map((data: any) => data.results),
      flatMap((players) =>
        forkJoin(
          players.map(player => {
            return this.http.get(`https://r6tab.com/api/player.php?p_id=${player.p_id}`).pipe(
              map((fulldetails: any) => {
                fulldetails.favdefender = fulldetails.favdefender.replace(':', '-');
                fulldetails.favattacker = fulldetails.favattacker.replace(':', '-');
                fulldetails.operators = this.getOperators(fulldetails.operators);
                fulldetails.operators_season = this.getOperatorsSeason(fulldetails.operators_season);
                return { ...fulldetails, ...player };
              }));
          })
        )
      )
    );
  }

**Comment by iNiizz** [comment]
then i used this to get the playerId from the data to gain access to the operator array

**Comment by iNiizz** [comment]
https://r6tab.com/images/operators/2-14.png thats the url for the operator images

**Comment by MrDrache333** [comment]
Actually I mean the ability to Upload a Screenshot of the Stats-Table in game to [R6Tab](https://r6tab.com/score2ranks) and get the Payers back which are playing with you...😂 But nevermind. I found a Solution for this Problem. I use another [API](https://gitlab.com/siege-insights/r6tab-java-api-client) for this. It works perfectly 😃 

For Example:
`R6TabApi api = new R6TabApiImpl();
  // Extract UUIDs from a scoreboard screenshot
  List<UUID> ids = api.getUserUUIDFromScreenshot(someFile);
  if (ids != null){
  for (UUID id : ids) {
  Player player = api.getPlayerByUUID(id);
  if (player != null) {
  //Do some fancy stuff
  }
  }
  }
`

**Comment by iNiizz** [comment]
ohh i know what you mean, like what King George has on his score board in game?
