### ISSUE TITLE
Add reference to the Java API client

### ISSUE THREAD

**Issue by RAYs3T** [Tabwire/R6Tab-API#2]
I've started creating a Java API client for your API. The API-client is still work-in-progress and will get a lot of other features in the next few days.

If you like you can add a link from this site, so other users can find it easily. Any contribution is welcome!

See: 
https://gitlab.com/siege-insights/r6tab-java-api-client

I'll create a pull request with the addition in the README soon.

**Comment by AustinLeath** [comment]
I don't necessarily see this as an issue, closed.
