### ISSUE TITLE
The rainbow 6 tab api doesnt seem to update until and unless we open a profile in the website

### ISSUE THREAD

**Issue by xybercommander** [Tabwire/R6Tab-API#26]
When I call the results, it shows
`{
"results":
[
  {"p_id":"236e3400-ba6a-459a-b67a-6525321e72b7",
   "p_name":"HiddenBlade-AG7",
   "p_level":149,
   "p_platform":"uplay",
   "p_user":"236e3400-ba6a-459a-b67a-6525321e72b7",
   "p_currentmmr":2300,
   "p_currentrank":10,
   "verified":0,
   "kd":58}
],
"totalresults":1
}
`

The above request was called at 6:48pm (IST)

But after visiting the profile at 6:50pm (IST), the stats get changed to the original ones
`{"results":[{"p_id":"236e3400-ba6a-459a-b67a-6525321e72b7","p_name":"HiddenBlade-AG7","p_level":156,"p_platform":"uplay","p_user":"236e3400-ba6a-459a-b67a-6525321e72b7","p_currentmmr":2682,"p_currentrank":14,"verified":0,"kd":60}],"totalresults":1}`

Clearly the level and kd changes can be seen

**Comment by RAYs3T** [comment]
Had to deal with the same issue. Implemented a work-a-round by fetching the refresh site....

See https://github.com/RAYs3T/r6tab-java-api-client/blob/master/src/main/java/com/gitlab/siegeinsights/r6tab/api/impl/R6TabApiService.java#L98

and https://github.com/RAYs3T/r6tab-java-api-client/blob/master/src/main/java/com/gitlab/siegeinsights/r6tab/api/Constants.java#L15

But this is only possible every x minutes
