### ISSUE TITLE
api not Available any more ? 

### ISSUE THREAD

**Issue by Mbivoid** [Tabwire/R6Tab-API#29]

**Comment by Pierce01** [comment]
They changed their endpoints.

Search: `https://r6.apitab.com/search/${platform}/${name}`

Player: `https://r6.apitab.com/player/${id}`

Image CDN: `https://cdn.tab.one/r6/images/`

**Comment by Mbivoid** [comment]
> They changed their endpoints.
> 
> Search: `https://r6.apitab.com/search/${platform}/${name}`
> 
> Player: `https://r6.apitab.com/player/${id}`
> 
> Image CDN: `https://cdn.tab.one/r6/images/`

Thank you man

**Comment by Pierce01** [comment]
1fd6635 has everything docuemented now! Hope this helps 👍
