### ISSUE TITLE
Not updated for newest ranks

### ISSUE THREAD

**Issue by andreasrtv** [Tabwire/R6Tab-API#31]
The API still uses the old ranks and does not account for the new ranks (Copper V, Bronze V, Silver V and the removed Gold IV)

Old ranks:
![image](https://user-images.githubusercontent.com/31826825/78697416-0f7d0080-7901-11ea-8681-6a938ddf52b0.png)

New ranks:
![image](https://user-images.githubusercontent.com/31826825/78697411-0c821000-7901-11ea-90bf-c4965ed8aedf.png)

**Comment by Pierce01** [comment]
When asked in the Discord this was the response. I'll update the docs showing this, my apologies for the delay in response.
![response](https://owo.whats-th.is/8dveQ9p.png)

**Comment by AustinLeath** [comment]
Interesting, I do think that we should track all of the ranks to provide the most accurate stats as possible, Nader disagree's, therefore, I disagree.
