### ISSUE TITLE
Incorrect documentation for leaderboard

### ISSUE THREAD

**Issue by AleksanderWalencik** [Tabwire/R6Tab-API#33]
Under leaderboard, it states that to select platform you must use values:

xbl - for xbox
psn - for playstation
uplay - for pc

However, it always returns Windows

*** FIX ***
If you pass:

xbox - for xbox
playstation - for playstation
windows - for pc

You will get desired result.

**Comment by Tabwire** [comment]
Will fix the docs. Thank you!
