### ISSUE TITLE
Avatars

### ISSUE THREAD

**Issue by hebercrvg** [Tabwire/R6Tab-API#35]
Hi there. Is it possible to include the player avatar url in the response of the SEARCH endpoint?

**Comment by Mbivoid** [comment]
Hello , 
 Is it possible to get  Aliases  and Daily Matches ?

**Comment by Pierce01** [comment]
IMHO I don't believe returning the players avatar would have much of a point. A players avatar URL is simply `https://ubisoft-avatars.akamaized.net/${p_id}/default_146_146.png`. The regular search response responds with the `p_id` so you could easily format that link with the player's ID. I believe that's what R6Tab does on the frontend, but I could be mistaken.

Example: https://ubisoft-avatars.akamaized.net/2d99b95f-d15e-43c0-b6cd-8c3cdd9da704/default_146_146.png

**Comment by hebercrvg** [comment]
Sorry, I didn't know about this url.  Thanks for listening.  I suggest putting in the documentation on this URL, as it may be the question of other people.  Thank you!
