### ISSUE TITLE
Resigns Stats problem 

### ISSUE THREAD

**Issue by Mbivoid** [Tabwire/R6Tab-API#37]
At **ranked** child , Api is keep returning same stats for all resigns

**Comment by Cryptizism** [comment]
The new season unified all ranked stats and rank stats are not region locked.
This could be found [here](https://www.ubisoft.com/en-gb/game/rainbow-six/siege/game-info/seasons/steelwave#patchnotes-header) under the unified rank section.

**Comment by Mbivoid** [comment]
Thank you ,Now I got it 😊
