### ISSUE TITLE
403 forbidden

### ISSUE THREAD

**Issue by cookieforpres** [Tabwire/R6Tab-API#38]
I tried calling the api with a python script and got an error the whole point of a api.

**Comment by Pierce01** [comment]
It would help if you could include which endpoint you're using :)

**Comment by c12i** [comment]
Getting the same on `/search/:platform/:name` and `/player/:p_id`

**Comment by RAYs3T** [comment]
https://twitter.com/tabwire/status/1317928952317530114

**Comment by c12i** [comment]
well that sucks

**Comment by Pierce01** [comment]
Hopefully applications open for independent developers.
