### ISSUE TITLE
API calls are counted as "profile visits"

### ISSUE THREAD

**Issue by RAYs3T** [Tabwire/R6Tab-API#4]
I've noticed something that is properly a mistake.
If you request the API, this request is counted as profile visit.

Or is that intended?
@AustinLeath

**Comment by Tabwire** [comment]
Yes, that's intended as you viewed that profile.

**Comment by AustinLeath** [comment]
The api is the same api that our internal site calls so I guess we made it that way on purpose. I will see if we can get that removed, but if it is too much of a hassle it will stay.

**Comment by RAYs3T** [comment]
Or simply add a boolean (`noVisitIncrease=true`).

Because if you build something like a Teamspeak-Bot, you have to check the profile once every x for changes.

From my point of view - A visit should only be increased by  a person which is opening the profile.

**Comment by AustinLeath** [comment]
Yeah, this will not change, as @Tabwire stated above it is done on purpose

**Comment by AustinLeath** [comment]
Technically this would work. However, this is the way it is intended.
