### ISSUE TITLE
How can I get the KEY API?

### ISSUE THREAD

**Issue by Dragondrax** [Tabwire/R6Tab-API#42]
Hello .. a while ago I sent you an email requesting the KEY API, you informed me that it was not necessary and could be used smoothly ... today the API KEY is needed, I am always having the same feedback ..
{"authorized": false, "API": {"code": "NO_KEY"}, "found": false, "status": 403, "error": "Not authorized!", "message": "You need an API key. "," contact ":" https: \ / \ / tabstats.com \ / contact "}
I already sent an email, but no answer .. how can I proceed?
Thank you

**Comment by RAYs3T** [comment]
Well they don't do it anymore...
https://twitter.com/tabwire/status/1317928952317530114

**Comment by Pierce01** [comment]
Hopefully applications open for independent developers.

**Comment by Dragondrax** [comment]
Good night, is there any way I can make sure with you that I am using the API correctly, so that I can use it again? I was in the final stages of developing my app.

I await reply.


ATT. Igor

Obter o Outlook para Android<https://aka.ms/ghei36>
________________________________

**Comment by Pierce01** [comment]
@Dragondrax What do you mean? Like if you're handling response codes properly or accessing the correct information from the API? All the responses are documented, and it's safe to assume that if you don't get a 200 response/status code you did something incorrectly.

**Comment by Dragondrax** [comment]
Good afternoon, apparently it is giving error due to the lack of the KEY key, because previously I was able to use the API normally. How can I receive this KEY?

Obter o Outlook para Android<https://aka.ms/ghei36>
________________________________

**Comment by Pierce01** [comment]
You cannot at this time. Please refer to 12edb47

**Comment by Dragondrax** [comment]
Good night but I have been using the API for more than 1 month and when I asked if it was necessary at the time, KEY said no. I have the development process at the end of my application, is there any way I can do it? Perhaps demonstrating my use and proving that it is not abusive or related. I thank you for your attention

**Comment by Pierce01** [comment]
You will need to contact Nader. I do not work for Tabwire nor do I give out keys, I simply update the documentation when updates are relayed to me.

I genuinely do apologize for this inconvenience.

**Comment by Dragondrax** [comment]
how can i contact him?

Obter o Outlook para Android<https://aka.ms/ghei36>
________________________________

**Comment by Pierce01** [comment]
I recommend asking him through the Discord (discord.gg/tabwire).
