### ISSUE TITLE
Return values like the season ranks as an array instead of single fields

### ISSUE THREAD

**Issue by RAYs3T** [Tabwire/R6Tab-API#5]
Returning the seasons like this (one field for each season) isn't the most convenient way
```
... 
"season11rank": "20",
"season10rank": "20",
"season9rank": "20",
...
```

Returning them as an array would make changes / adjustments for new seasons much more easy.

For example:
```
...
    season_stats: [
        {
            season_id: 9,
            mmr: 4820,
            rank: 20
         }, {
            season_id: 10,
            mmr: 3100,
            rank: 18
        }
     ....
    ],


Adding the season names would be an extra 🥇

**Comment by Tabwire** [comment]
Smart! Will fix that ASAP.

**Comment by RAYs3T** [comment]
@Tabwire Let me know once you changed it, then i will update my Java API implementation ASAP and add the seasons ;)

**Comment by Tabwire** [comment]
When we update anything, we keep the old values and add extra values and
post an update on the gitgub that a function will be removed in 30 days. So
no worries, nothing will crash even if we update our code because we're
adding extra not removing old stats.
