### ISSUE TITLE
get Latest Data

### ISSUE THREAD

**Issue by Mohsen322** [Tabwire/R6Tab-API#8]
hi, thanks for your great api
how can i get the latest data with player id?
i mean updated data.
how can i send a request for getting data from now, not 10 hours or 12 hours ago...

**Comment by Mohsen322** [comment]
i need an option like **REFRESH** item in the r6tab website

**Comment by RAYs3T** [comment]
I would assume that this is by design not possible.
This way they can protect the original/official API from beieng spammed with all these requests.

But i agree that this would be nice.

**Comment by RAYs3T** [comment]
As Work-A-Round you can request the profile with the option `&updatenow=true` set, before you send the real API query.

For example:
First: https://r6tab.com/21e4e8e4-b70a-4f8a-be4d-d0db7c8c9076&updatenow=true

Then: https://r6tab.com/api/player.php?p_id=21e4e8e4-b70a-4f8a-be4d-d0db7c8c9076

**Comment by Mohsen322** [comment]
Thanks for answer
Hmm... look nice idea
But it would be better if add this parameter to main api
Thanks again dude
